import Head from "next/head";
import Hero from "../components/Hero";
import Trending from "../components/Trending";
import Superhero from "../components/Superhero";
import Footer2 from "../components/Footer2";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Luth Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading="Mau nonton film, acara Tv, dll secara gratis ?" message="Lihat dimana saja dan kapan saja tanpa iklan pula" />
      <Trending />
      <Superhero />
      <Footer2 />
    </div>
  );
}
